/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthorizedImport } from './routes/unauthorized'
import { Route as PageImport } from './routes/page'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as IndexImport } from './routes/index'
import { Route as EcommerceProductsImport } from './routes/ecommerce/products'
import { Route as EcommerceOrdersImport } from './routes/ecommerce/orders'
import { Route as CrmLeadsImport } from './routes/crm/leads'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedAnalyticsImport } from './routes/_protected/analytics'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as ProtectedUserIndexImport } from './routes/_protected/user/index'
import { Route as ProtectedManagerIndexImport } from './routes/_protected/manager/index'
import { Route as ProtectedAdminIndexImport } from './routes/_protected/admin/index'
import { Route as ProtectedCrmCustomersImport } from './routes/_protected/crm/customers'

// Create/Update Routes

const UnauthorizedRoute = UnauthorizedImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EcommerceProductsRoute = EcommerceProductsImport.update({
  id: '/ecommerce/products',
  path: '/ecommerce/products',
  getParentRoute: () => rootRoute,
} as any)

const EcommerceOrdersRoute = EcommerceOrdersImport.update({
  id: '/ecommerce/orders',
  path: '/ecommerce/orders',
  getParentRoute: () => rootRoute,
} as any)

const CrmLeadsRoute = CrmLeadsImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  id: '/_protected/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedAnalyticsRoute = ProtectedAnalyticsImport.update({
  id: '/_protected/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedUserIndexRoute = ProtectedUserIndexImport.update({
  id: '/_protected/user/',
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedManagerIndexRoute = ProtectedManagerIndexImport.update({
  id: '/_protected/manager/',
  path: '/manager/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedAdminIndexRoute = ProtectedAdminIndexImport.update({
  id: '/_protected/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedCrmCustomersRoute = ProtectedCrmCustomersImport.update({
  id: '/_protected/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof rootRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsImport
      parentRoute: typeof rootRoute
    }
    '/ecommerce/orders': {
      id: '/ecommerce/orders'
      path: '/ecommerce/orders'
      fullPath: '/ecommerce/orders'
      preLoaderRoute: typeof EcommerceOrdersImport
      parentRoute: typeof rootRoute
    }
    '/ecommerce/products': {
      id: '/ecommerce/products'
      path: '/ecommerce/products'
      fullPath: '/ecommerce/products'
      preLoaderRoute: typeof EcommerceProductsImport
      parentRoute: typeof rootRoute
    }
    '/_protected/crm/customers': {
      id: '/_protected/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof ProtectedCrmCustomersImport
      parentRoute: typeof rootRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/manager/': {
      id: '/_protected/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ProtectedManagerIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/user/': {
      id: '/_protected/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof ProtectedUserIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/page': typeof PageRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/ecommerce/orders': typeof EcommerceOrdersRoute
  '/ecommerce/products': typeof EcommerceProductsRoute
  '/crm/customers': typeof ProtectedCrmCustomersRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/manager': typeof ProtectedManagerIndexRoute
  '/user': typeof ProtectedUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/page': typeof PageRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/ecommerce/orders': typeof EcommerceOrdersRoute
  '/ecommerce/products': typeof EcommerceProductsRoute
  '/crm/customers': typeof ProtectedCrmCustomersRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/manager': typeof ProtectedManagerIndexRoute
  '/user': typeof ProtectedUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/page': typeof PageRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/ecommerce/orders': typeof EcommerceOrdersRoute
  '/ecommerce/products': typeof EcommerceProductsRoute
  '/_protected/crm/customers': typeof ProtectedCrmCustomersRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/manager/': typeof ProtectedManagerIndexRoute
  '/_protected/user/': typeof ProtectedUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/page'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/analytics'
    | '/settings'
    | '/crm/leads'
    | '/ecommerce/orders'
    | '/ecommerce/products'
    | '/crm/customers'
    | '/admin'
    | '/manager'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/page'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/analytics'
    | '/settings'
    | '/crm/leads'
    | '/ecommerce/orders'
    | '/ecommerce/products'
    | '/crm/customers'
    | '/admin'
    | '/manager'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/not-found'
    | '/page'
    | '/unauthorized'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/analytics'
    | '/_protected/settings'
    | '/crm/leads'
    | '/ecommerce/orders'
    | '/ecommerce/products'
    | '/_protected/crm/customers'
    | '/_protected/admin/'
    | '/_protected/manager/'
    | '/_protected/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  PageRoute: typeof PageRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  EcommerceOrdersRoute: typeof EcommerceOrdersRoute
  EcommerceProductsRoute: typeof EcommerceProductsRoute
  ProtectedCrmCustomersRoute: typeof ProtectedCrmCustomersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedManagerIndexRoute: typeof ProtectedManagerIndexRoute
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  PageRoute: PageRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  EcommerceOrdersRoute: EcommerceOrdersRoute,
  EcommerceProductsRoute: EcommerceProductsRoute,
  ProtectedCrmCustomersRoute: ProtectedCrmCustomersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedManagerIndexRoute: ProtectedManagerIndexRoute,
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/not-found",
        "/page",
        "/unauthorized",
        "/_auth/login",
        "/_auth/register",
        "/_protected/analytics",
        "/_protected/settings",
        "/crm/leads",
        "/ecommerce/orders",
        "/ecommerce/products",
        "/_protected/crm/customers",
        "/_protected/admin/",
        "/_protected/manager/",
        "/_protected/user/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/page": {
      "filePath": "page.tsx"
    },
    "/unauthorized": {
      "filePath": "unauthorized.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx"
    },
    "/_protected/analytics": {
      "filePath": "_protected/analytics.tsx"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx"
    },
    "/crm/leads": {
      "filePath": "crm/leads.tsx"
    },
    "/ecommerce/orders": {
      "filePath": "ecommerce/orders.tsx"
    },
    "/ecommerce/products": {
      "filePath": "ecommerce/products.tsx"
    },
    "/_protected/crm/customers": {
      "filePath": "_protected/crm/customers.tsx"
    },
    "/_protected/admin/": {
      "filePath": "_protected/admin/index.tsx"
    },
    "/_protected/manager/": {
      "filePath": "_protected/manager/index.tsx"
    },
    "/_protected/user/": {
      "filePath": "_protected/user/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
